import picomatch from "picomatch";
import { addedLines, type FileDiff } from "./diff";

export const DEFAULT_EXCLUDES = [
  "**/package-lock.json",
  "**/npm-shrinkwrap.json",
  "**/yarn.lock",
  "**/pnpm-lock.yaml",
  "**/bun.lock",
  "**/bun.lockb",
  "**/Cargo.lock",
  "**/go.sum",
  "**/poetry.lock",
  "**/uv.lock",
  "**/Gemfile.lock",
  "**/composer.lock",
  "**/*.min.js",
  "**/*.min.css",
  "**/*.map",
  "**/*.snap",
  "**/*.generated.*",
  "**/*.pb.go",
  "**/*_pb2.py",
  "**/__generated__/**",
  "**/dist/**",
  "**/build/**",
  "**/out/**",
  "**/.next/**",
  "**/coverage/**",
  "**/vendor/**",
  "**/node_modules/**",
];

const GENERATED_MARKER = /@generated|DO NOT EDIT|auto-generated|autogenerated/i;

export interface Skipped {
  path: string;
  reason: string;
}

export function partitionFiles(
  files: FileDiff[],
  extraExcludes: string[],
): { kept: FileDiff[]; skipped: Skipped[] } {
  const isExcluded = picomatch([...DEFAULT_EXCLUDES, ...extraExcludes], { dot: true });
  const kept: FileDiff[] = [];
  const skipped: Skipped[] = [];

  for (const file of files) {
    if (file.binary) skipped.push({ path: file.path, reason: "binary" });
    else if (isExcluded(file.path)) skipped.push({ path: file.path, reason: "generated, vendored, or excluded" });
    else if (hasGeneratedMarker(file)) skipped.push({ path: file.path, reason: "marked as generated" });
    else kept.push(file);
  }
  return { kept, skipped };
}

function hasGeneratedMarker(file: FileDiff): boolean {
  if (file.status !== "added") return false;
  return addedLines(file)
    .slice(0, 5)
    .some((l) => GENERATED_MARKER.test(l.text));
}
